test:
  image: python:3.6
  stage: test
  tags:
  - docker-python
  - cassander
  except:
    - master
  script:
  - pip install -U virtualenv pip
  - python --version
  - make test-unit-all
  - make test-lint-errors

test-master:
  image: python:3.6
  stage: test
  tags:
  - docker-python
  - cassander
  only:
    - master
  script:
  - pip install -U virtualenv pip
  - python --version
  - make test-unit-all
  - make test-lint-errors
  - make test-lint || true

deploy-dev:
  stage: deploy
  tags:
  - jupyter-shell
  - cassander
  only:
    - development
  script:
  - source $VIRTUALENVWRAPPER_HOOK_DIR/development/bin/activate
  - pip install -U -r dev-requirements.txt
  - pip install .
  - pip install --upgrade --no-deps --force-reinstall .

deploy-dev-docs:
  stage: deploy
  tags:
  - jupyter-shell
  - cassander
  only:
    - development
  script:
  - ls -lah $DATAHOME
  - test -d $DATAHOME/docs || mkdir $DATAHOME/docs
  - make docs-ci
  - rsync -avr --delete-after --checksum docs/_build/html/ $DATAHOME/docs

deploy-master:
  stage: deploy
  tags:
  - jupyter-shell
  - cassander
  only:
    - master
  script:
  - source $VIRTUALENVWRAPPER_HOOK_DIR/master/bin/activate
  - pip install -U -r dev-requirements.txt
  - pip install .
  - pip install --upgrade --no-deps --force-reinstall .
